server: 
  port: 9008

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true     #访问路径可以显示IP地址,跨域访问

spring: 
  application:  
    name: user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_user?characterEncoding=UTF8&useSSL=false
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 127.0.0.1
  rabbitmq:
    host: 127.0.0.1

jtw:
  config:
   key: itcast
   ttl: 3600000
