server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  datasource:
    driverClassName: com.mysql.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
aliyun:
  sms:
   accessKeyId: LTAI4Fdv21qmTx2AVFKv5kAQ
   accessKeySecret: zvFPo5Z2ZV0ULqOlmHPvPMeXgeQgre
   template_code: SMS_177250912
   sign_name: 十次方