server:
  port: 9010

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true     #访问路径可以显示IP地址,跨域访问
jwt:
  config:
    key: itcast
spring:
  application:
    name: friend
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_friend?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    database: MySQL
    show‐sql: true

