server:
  port: 9011

spring:
  application:
    name: mabager
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_base?characterEncoding=utf-8&useSSL=false
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true     #\u8BBF\u95EE\u8DEF\u5F84\u53EF\u4EE5\u663E\u793AIP\u5730\u5740,\u8DE8\u57DF\u8BBF\u95EE

zuul:
  routes:
    tensquare-base:
      path: /bash/**
      serviceId: base
    tensquare-user:
      path: /user/**
      serviceId: user
    tensquare-qa:
      path: /qa/**
      serviceId: qa
